### ISSUE TITLE
Linked references filter items overlap when their height is large

### ISSUE THREAD

**Issue by MaxLinWorm** [rcvd/roam-css-system#79]
Using the Craft theme.

Without fix:
![image](https://user-images.githubusercontent.com/68432385/177213184-d6287432-870b-4916-8312-8ddf9a4bdc5f.png)

With fix:

![image](https://user-images.githubusercontent.com/68432385/177213267-467e585f-4e44-460c-a9f4-aff5a3564d7b.png)

Fixed with:

```CSS
div.bp3-transition-container.bp3-popover-enter-done > div.bp3-popover[style*='transform-origin'] > div.bp3-popover-content > div[style*='max-width: 600px'] > div[style*='display: flex'] > div:nth-child(4) > div > div >button {
    color: red !important;
    height: auto;
}
```

I'm sure the selector could be improved.

Also, see fix for the selected linked reference filter item:
