### ISSUE TITLE
Adding support for search term highlight colour

### ISSUE THREAD

**Issue by mil-ad** [rcvd/roam-css-system#95]
It'd be great if you could add a variable for the search term highlight colors that shows up in find menu/popup.

The CSS path below works but there's probably a more robust one:

```css
.rm-find-or-create-wrapper .rm-menu-item .rm-search-list-item span span {
    background-color: #427b58 !important
}
```

**Comment by rcvd** [comment]
There is a variable for it:

```css
:root {
   --span--highlighted: #427b58 !important
}
```
